### ISSUE TITLE
Log spam

### ISSUE THREAD

**Issue by NevendyND** [Glyceri/FFXIVPetRenamer#2]
Just wanted to say that i get a Log spam from this Plugin

```
13:47:22.036 | ERR Exception during raise of "Void <InvokeSafely>b__0()"
System.InvalidOperationException: Nullable object must have a value.
   at PetRenamer.Core.Updatable.Updatables.NameChangeUpdatable.Update(Framework frameWork) in /work/repo/PetRenamer/Core/Updatable/Updatables/NameChangeUpdatable.cs:line 48
   at PetRenamer.Core.Updatable.UpdatableHandler.MainUpdate(Framework framework) in /work/repo/PetRenamer/Core/Updatable/UpdatableHandler.cs:line 28
   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act) in C:\goatsoft\companysecrets\dalamud\Utility\EventHandlerExtensions.cs:line 96
```

Its the same Error a few Hundred Times for 11 seconds.

**Comment by Glyceri** [comment]
Sorry, incredibly dumb error to have overlooked. Should be fixed in tonights update 😅
